name: flutter_darwin_notification_example
description: Demonstrates how to use the flutter_darwin_notification plugin.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_darwin_notification:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
