name: flutter_darwin_notification
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/modool/flutter_darwin_notification

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterDarwinNotficationPlugin
