name: Flutter Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.9.x' 
        channel: 'stable' 
    - run: flutter pub get
    - run: flutter test
    - run: cd ./example
    - run: flutter build aot
